steps:
  - name: deploy
    image: alpine:3.20
    environment:
      SSH_HOST:
        from_secret: SSH_HOST
      PROJECT_DIRECTORY:
        from_secret: PROJECT_DIRECTORY
      SSH_KEY:
        from_secret: SSH_KEY
      REGISTRY_IMAGE_TAG:
        from_secret: REGISTRY_IMAGE_TAG
    commands:
      - apk add openssh
      - mkdir -p /root/.ssh/
      - echo "$SSH_KEY" | tr -d '\r' > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /root/.ssh/config
      - ssh "$SSH_HOST" "
        cd "$PROJECT_DIRECTORY";
        docker-compose down;
        docker image rm "$REGISTRY_IMAGE_TAG" || true;
        git restore . && git pull origin "$CI_COMMIT_BRANCH";
        docker-compose up -d;"
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: SERVICE_QUEUE_DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: SERVICE_QUEUE_DISCORD_WEBHOOK_TOKEN
      message: >
        {{#success build.status}}
          {{repo.name}} deployment #{{build.number}} {{build.status}}
        {{/success}}
    depends_on: deploy

when:
  - branch: Main
    event: push
