# Python test step for Woodpecker CI/CD

labels:
  platform: linux/amd64

steps:
  - name: test
    image: astral/uv:python3.13-trixie-slim
    # TODO: Add necessary environment variables below
    # environment: 
    #   variable:
    #     from_secret: variable
    commands:
      - uv sync --frozen --cache-dir /.cache/uv --link-mode=copy
      - export PATH=".venv/bin:$PATH"
      - pytest
    volumes:
      - /tmp/.uv:/.cache/uv # Optimization: Shared UV cache on local build server
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: SERVICE_QUEUE_DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: SERVICE_QUEUE_DISCORD_WEBHOOK_TOKEN
      message: >
        {{#success build.status}}
          ✅ [{{repo.name}}] Successful test for build #{{build.number}}
          Branch: {{commit.branch}}
          Commit: {{commit.sha}}:{{commit.message}}
          By: {{commit.author}}
        {{else}}
          ❌ [{{repo.name}}] Failed test for build #{{build.number}}
          Branch: {{commit.branch}}
          Commit: {{commit.sha}}:{{commit.message}}
          By: {{commit.author}}
        {{/success}}
    when:
      status: [ success, failure ]
      
when:
  - branch: master
    event:
      - push
      - manual
