# Python test step for Woodpecker CI/CD

labels:
  platform: linux/amd64

steps:
  - name: test
    image: astral/uv:python3.13-trixie-slim
    # TODO: Add necessary environment variables below
    # environment: 
    #   variable:
    #     from_secret: variable
    commands:
      - uv sync --frozen
      - export PATH=".venv/bin:$PATH"
      - pytest
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: >
        {{#success build.status}}
          {{repo.name}}: Test step for build #{{build.number}} output {{build.status}}
        {{/success}}

when:
  - branch: master
    event:
      - push
      - manual
